"""Render the generated curriculum coverage audit and layered roadmap."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from tools.checks.scope import LAYERS, check_scope
from tools.model import KnowledgePoint, Roadmap, load_roadmap

AUDIT_PATH = Path("docs/audits/015-coverage-audit.md")
ROADMAP_PATH = Path("docs/curriculum-roadmap.md")


def _yaml(path: Path) -> dict:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise TypeError(f"{path}: expected a YAML mapping")
    return raw


def _cell(value: object) -> str:
    text = str(value) if value not in (None, "") else "—"
    return text.replace("|", "\\|").replace("\n", " ")


def _joined(values: list[str]) -> str:
    return ", ".join(values) if values else "—"


def _evidence_lines(point: KnowledgePoint) -> list[str]:
    lines: list[str] = []
    for modality in sorted(point.evidence_by_modality, key=str.encode):
        evidence = point.evidence_by_modality[modality]
        lessons = [
            f"{anchor.path} :: {anchor.heading} :: cell {anchor.cell_ordinal}"
            for anchor in evidence.lesson_anchors
        ]
        practices = [item.id for item in evidence.practices]
        assessments = [item.id for item in evidence.assessments]
        lines.extend(
            [
                f"- **{modality} lessons:** {_joined(sorted(lessons, key=str.encode))}",
                f"- **{modality} practices:** {_joined(sorted(set(practices), key=str.encode))}",
                (
                    f"- **{modality} assessments:** "
                    f"{_joined(sorted(set(assessments), key=str.encode))}"
                ),
            ]
        )
    return lines


def _render_audit(roadmap: Roadmap, inventory: dict) -> str:
    counts = inventory.get("counts") or {}
    points = sorted(roadmap.knowledge_points, key=lambda item: item.id.encode("utf-8"))
    requirement_counts = {name: 0 for name in ("required", "bridge", "optional")}
    coverage_counts = {name: 0 for name in ("covered", "partial", "missing")}
    for point in points:
        requirement_counts[point.requirement] = requirement_counts.get(point.requirement, 0) + 1
        coverage_counts[point.coverage] = coverage_counts.get(point.coverage, 0) + 1
    lines = [
        "<!-- GENERATED by tools/render_curriculum_roadmap.py; do not edit. -->",
        "# Plan 015 coverage audit",
        "",
        "This report renders the adjudication in `curriculum/coverage-map.yaml` against the",
        "deterministic evidence inventory in `curriculum/material-inventory.yaml`.",
        "Assessment ids are reported separately and never satisfy the unit-practice rule.",
        "",
        "## Corpus and status totals",
        "",
        "| Measure | Count |",
        "|---|---:|",
    ]
    for label, key in (
        ("Inventoried notebooks", "unit_notebooks"),
        ("Unit practices", "unit_practices"),
        ("Mock notebooks", "mock_notebooks"),
    ):
        lines.append(f"| {label} | {_cell(counts.get(key, 0))} |")
    for label, values in (("Requirement", requirement_counts), ("Coverage", coverage_counts)):
        for name in sorted(values, key=str.encode):
            lines.append(f"| {label}: {name} | {values[name]} |")
    lines.extend(["", "## Atomic-target audit", ""])
    for point in points:
        lines.extend(
            [
                f"### {point.id}",
                "",
                f"- **Layer:** {point.layer}",
                f"- **Requirement:** {point.requirement}",
                f"- **Coverage:** {point.coverage}",
                f"- **Destination:** {point.destination or '—'}",
                f"- **Dependencies:** {_joined(point.depends_on)}",
                f"- **Shipped concepts:** {_joined(point.shipped_concepts)}",
                f"- **Modalities missing:** {_joined(point.modalities_missing)}",
                f"- **Rationale:** {point.rationale}",
                f"- **Consequence:** {point.consequence}",
                "",
            ]
        )
        lines.extend(_evidence_lines(point))
        practices = sorted(
            {
                item.id
                for evidence in point.evidence_by_modality.values()
                for item in evidence.practices
            },
            key=str.encode,
        )
        assessments = sorted(
            {
                item.id
                for evidence in point.evidence_by_modality.values()
                for item in evidence.assessments
            },
            key=str.encode,
        )
        lines.extend(
            [
                "",
                f"Practices: {_joined(practices)}",
                "",
                f"Assessments: {_joined(assessments)}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def _required_rounds(root: Path) -> dict[str, set[str]]:
    topics = _yaml(root / "curriculum" / "official-topics.yaml")
    return {
        str(row["id"]): {str(value) for value in row.get("required_for") or []}
        for row in topics.get("atomic_targets") or []
    }


def _render_roadmap(root: Path, roadmap: Roadmap) -> str:
    rounds = _required_rounds(root)
    lines = [
        "<!-- GENERATED by tools/render_curriculum_roadmap.py; do not edit. -->",
        "# Curriculum roadmap",
        "",
        "The shipped-content contract remains in `syllabus.md`.",
        "This roadmap records acknowledged shipped and planned curriculum state.",
        "",
        "## Exit paths",
        "",
        "### Round 1 exit",
        "",
    ]
    r1 = [
        point
        for point in roadmap.knowledge_points
        if "round-1" in rounds.get(point.id, set())
    ]
    r2 = [
        point
        for point in roadmap.knowledge_points
        if "round-2" in rounds.get(point.id, set())
    ]
    for label, points in (("Round 1", r1), ("Round 2", r2)):
        if label == "Round 2":
            lines.extend(["### Round 2 exit", ""])
        gaps = sum(point.coverage != "covered" for point in points)
        lines.extend(
            [
                f"{len(points)} required/bridge atomic targets; {gaps} acknowledged gaps.",
                "",
            ]
        )
    lines.extend(["## Layered knowledge points", ""])
    for layer in LAYERS:
        lines.extend(
            [
                f"### {layer}",
                "",
                "| Knowledge point | Requirement | Coverage | Destination | Dependencies |",
                "|---|---|---|---|---|",
            ]
        )
        points = sorted(
            (point for point in roadmap.knowledge_points if point.layer == layer),
            key=lambda item: item.id.encode("utf-8"),
        )
        if not points:
            lines.append("| — | — | — | — | — |")
        for point in points:
            lines.append(
                "| "
                + " | ".join(
                    _cell(value)
                    for value in (
                        point.id,
                        point.requirement,
                        point.coverage,
                        point.destination,
                        _joined(point.depends_on),
                    )
                )
                + " |"
            )
        lines.append("")
    lines.extend(
        [
            "## Planned units",
            "",
            "| Unit | Title | Layer | Hours | Schedule action | Prerequisites | Owns |",
            "|---|---|---|---:|---|---|---|",
        ]
    )
    for unit in sorted(roadmap.planned_units, key=lambda item: item.id.encode("utf-8")):
        hours = f"{unit.estimated_hours.minimum:g}–{unit.estimated_hours.maximum:g}"
        lines.append(
            "| "
            + " | ".join(
                _cell(value)
                for value in (
                    unit.id,
                    unit.title,
                    unit.layer,
                    hours,
                    unit.schedule_action,
                    _joined(unit.prerequisites),
                    _joined(unit.knowledge_points),
                )
            )
            + " |"
        )
    if not roadmap.planned_units:
        lines.append("| — | — | — | — | — | — | — |")
    return "\n".join(lines).rstrip() + "\n"


def render_documents(root: str | Path) -> dict[Path, str]:
    root = Path(root).resolve()
    roadmap = load_roadmap(root)
    inventory = _yaml(root / "curriculum" / "material-inventory.yaml")
    return {
        AUDIT_PATH: _render_audit(roadmap, inventory),
        ROADMAP_PATH: _render_roadmap(root, roadmap),
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", default=".")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    root = Path(args.root).resolve()
    report = check_scope(root)
    if report.errors:
        for error in report.errors:
            print(f"ERROR scope-check: {error}", file=sys.stderr)
        return 1
    rendered = render_documents(root)
    stale: list[str] = []
    for relative, content in rendered.items():
        path = root / relative
        if args.check:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != content:
                stale.append(relative.as_posix())
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    if stale:
        for path in stale:
            print(f"STALE {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
